=== sec3-product/x-ray/coderrect/benchmark/concurrency-bugs/lib/apache-21285/httpd-2.0.46/docs/manual/style/modulesynopsis.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY % sitemap SYSTEM "sitemap.dtd">
%sitemap;

<!ELEMENT modulesynopsis (name , description, status, hint?, sourcefile?,
identifier? , compatibility? , summary? , seealso* , section*,
directivesynopsis*)>

<!ATTLIST modulesynopsis metafile CDATA  #REQUIRED>

<!ELEMENT directivesynopsis (name , description? , syntax? , default?
, contextlist? , override? , modulelist?, status?, compatibility? ,
usage?, seealso*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT status (#PCDATA)>

<!ELEMENT hint %Inline;>

<!ELEMENT identifier (#PCDATA)>

<!ELEMENT sourcefile (#PCDATA)>

<!ELEMENT compatibility %Inline;>

<!ELEMENT description %Inline;>

<!ATTLIST directivesynopsis  type CDATA  #IMPLIED
                             location CDATA  #IMPLIED >

<!ELEMENT syntax %Inline;>

<!ELEMENT default (#PCDATA | br)*>

<!ELEMENT contextlist (context+)+>

<!ELEMENT context (#PCDATA)>

<!ELEMENT override (#PCDATA)>

<!ELEMENT usage %Block;>

<!-- Used in index.xml -->
<!ELEMENT moduleindex (title, summary, seealso*, modulefilelist)>

<!ATTLIST moduleindex metafile CDATA  #REQUIRED>

<!-- Used in directive.xml -->
<!ELEMENT directiveindex (title | summary | modulefilelist)+>

<!ATTLIST directiveindex metafile CDATA  #REQUIRED>

<!-- Used in quickreference.xml -->
<!ELEMENT quickreference (title | summary | legend | modulefilelist)+>
<!ATTLIST quickreference metafile CDATA  #REQUIRED>

<!ELEMENT legend (table, table)>

=== sec3-product/x-ray/coderrect/benchmark/concurrency-bugs/lib/apache-21285/httpd-2.0.46/docs/manual/mod/mpm_winnt.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis metafile="mpm_winnt.xml.meta">

<name>mpm_winnt</name>
<description>This Multi-Processing Module is optimized for Windows
NT.</description>
<status>MPM</status>
<sourcefile>mpm_winnt.c</sourcefile>
<identifier>mpm_winnt_module</identifier>

<summary>
    <p>This Multi-Processing Module (MPM) is the default for the
    Windows NT operating systems. It uses a single control process
    which launches a single child process which in turn creates
    threads to handle requests</p>
</summary>

<directivesynopsis location="mpm_common"><name>CoreDumpDirectory</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>PidFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>Listen</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ListenBacklog</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MaxRequestsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ScoreBoardFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>SendBufferSize</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ThreadLimit</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ThreadsPerChild</name>
</directivesynopsis>

</modulesynopsis>
