=== sec3-product/x-ray/coderrect/benchmark/concurrency-bugs/lib/apache-21285/httpd-2.0.46/docs/manual/style/sitemap.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY % common SYSTEM "common.dtd">
%common;

<!-- <sitemap> is the root element -->
<!ELEMENT sitemap (title, summary?, seealso*, category*)>

<!ATTLIST sitemap metafile CDATA  #REQUIRED>

<!-- <indexpage> is another root element -->
<!ELEMENT indexpage (parentdocument, title, category*)>

<!ATTLIST indexpage metafile CDATA  #REQUIRED>

<!ELEMENT category (title, page*, modulefilelist? )>
<!ATTLIST category id ID #IMPLIED>

<!ELEMENT page (#PCDATA)>
<!ATTLIST page href CDATA #IMPLIED
               separate (yes | no) "no" >

<!ELEMENT modulefilelist (modulefile*) >
<!ELEMENT modulefile (#PCDATA) >

=== sec3-product/x-ray/coderrect/benchmark/concurrency-bugs/lib/apache-21285/httpd-2.0.46/docs/manual/index.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE indexpage SYSTEM "./style/sitemap.dtd">
<?xml-stylesheet type="text/xsl" href="./style/manual.en.xsl"?>

<indexpage metafile="index.xml.meta">
<parentdocument href="http://httpd.apache.org/docs-project/" />

<title>Apache HTTP Server Version 2.0 Documentation</title>

<category id="release"><title>Release Notes</title>
    <page href="new_features_2_0.html">New features with Apache 2.0</page>
    <page href="upgrading.html">Upgrading to 2.0 from 1.3</page>
    <page href="license.html">Apache License</page>
</category>

<category id="manual"><title>Reference Manual</title>
    <page href="install.html">Compiling and Installing</page>
    <page href="invoking.html">Starting</page>
    <page href="stopping.html">Stopping or Restarting</page>
    <page href="mod/directives.html">Run-time Configuration Directives</page>
    <page href="mod/quickreference.html">Directive Quick-Reference</page>
    <page href="mod/">Modules</page>
    <page href="mpm.html">Multi-Processing Modules (MPMs)</page>
    <page href="filter.html">Filters</page>
    <page href="handler.html">Handlers</page>
    <page href="programs/">Server and Supporting Programs</page>
    <page href="glossary.html">Glossary</page>
</category>    

<category id="usersguide"><title>Users' Guide</title>
    <page href="bind.html">Binding</page>
    <page href="configuring.html">Configuration Files</page>
    <page href="sections.html">Configuration Sections</page>
    <page href="content-negotiation.html">Content Negotiation</page>
    <page href="dso.html">Dynamic Shared Objects (DSO)</page>
    <page href="env.html">Environment Variables</page>
    <page href="logs.html">Log Files</page>
    <page href="urlmapping.html">Mapping URLs to the Filesystem</page>
    <page href="misc/perf-tuning.html">Performance Tuning</page>
    <page href="misc/security_tips.html">Security Tips</page>
    <page href="server-wide.html">Server-Wide Configuration</page>
    <page href="ssl/">SSL/TLS Encryption</page>
    <page href="suexec.html">Suexec Execution for CGI</page>
    <page href="misc/rewriteguide.html">URL Rewriting Guide</page>
    <page href="vhosts/">Virtual Hosts</page>
</category>

<category id="howto"><title>How-To / Tutorials</title>
    <page href="howto/auth.html">Authentication, Authorization, and Access
    Control</page>
    <page href="howto/cgi.html">CGI: Dynamic Content</page>
    <page href="howto/htaccess.html">.htaccess files</page>
    <page href="howto/ssi.html">Server Side Includes (SSI)</page>
    <page href="howto/public_html.html">Per-user Web Directories
    (public_html)</page>
</category>

<category id="platform"><title>Platform Specific Notes</title>
    <page href="platform/windows.html">Microsoft Windows</page>
    <page href="platform/netware.html">Novell NetWare</page>
    <page href="platform/ebcdic.html">EBCDIC Port</page>
</category>

<category id="other"><title>Other Topics</title>
    <page href="faq/">Frequently Asked Questions</page>
    <page href="sitemap.html">Sitemap</page>
    <page href="developer/">Documentation for Developers</page>
    <page href="misc/">Other Notes</page>
</category>

</indexpage>

=== sec3-product/x-ray/coderrect/benchmark/concurrency-bugs/lib/apache-21285/httpd-2.0.46/docs/manual/sitemap.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sitemap SYSTEM "./style/sitemap.dtd"  
  [ <!ENTITY allmodules SYSTEM "./mod/allmodules.xml"> ]
>
<?xml-stylesheet type="text/xsl" href="./style/manual.en.xsl"?>

<sitemap metafile="sitemap.xml.meta">

  <title>Sitemap</title>

<summary>
<p>This page lists the currently available documents of the
<a href="./">Apache HTTP Server Version 2.0 Documentation</a>.</p>
</summary>

<category id="release">
<title>Release Notes</title>
<page href="upgrading.html">Upgrading to 2.0 from 1.3</page>
<page href="new_features_2_0.html">New features with Apache 2.0</page>
<page href="license.html">Apache License</page>
</category>

<category id="using">
<title>Using the Apache HTTP Server</title>
<page href="install.html">Compiling and Installing Apache</page>
<page href="invoking.html">Starting Apache</page>
<page href="stopping.html">Stopping and Restarting the Server</page>
<page href="configuring.html">Configuration Files</page>
<page href="sections.html">How Directory, Location and Files sections work</page>
<page href="server-wide.html">Server-Wide Configuration</page>
<page href="logs.html">Log Files</page>
<page href="urlmapping.html">Mapping URLs to Filesystem Locations</page>
<page href="misc/security_tips.html">Security Tips</page>
<page href="dso.html">Dynamic Shared Object (DSO) support</page>
<page href="content-negotiation.html">Content Negotiation</page>
<page href="custom-error.html">Custom error responses</page>
<page href="bind.html">Setting which addresses and ports Apache uses</page>
<page href="mpm.html">Multi-Processing Modules (MPMs)</page>
<page href="env.html">Environment Variables in Apache</page>
<page href="handler.html">Apache's Handler Use</page>
<page href="filter.html">Filters</page>
<page href="suexec.html">suEXEC Support</page>
<page href="misc/perf-tuning.html">Performance Hints</page>
<page href="misc/rewriteguide.html">URL Rewriting Guide</page>
</category>

<category id="vhosts">
<title>Apache Virtual Host documentation</title>
<page separate="yes" href="vhosts/">Overview</page>
<page href="vhosts/name-based.html">Name-based Virtual Hosts</page>
<page href="vhosts/ip-based.html">IP-based Virtual Host Support</page>
<page href="vhosts/mass.html">Dynamically configured mass virtual hosting</page>
<page href="vhosts/examples.html">VirtualHost Examples</page>
<page href="vhosts/details.html">An In-Depth Discussion of Virtual Host Matching</page>
<page href="vhosts/fd-limits.html">File descriptor limitations</page>
<page href="dns-caveats.html">Issues Regarding DNS and Apache</page>
</category>

<category id="faq">
<title>Apache Server Frequently Asked Questions</title>
<page href="faq/">Overview</page>
<page separate="yes" href="faq/all_in_one.html">All on One Page</page>
<page href="faq/support.html">Support</page>
</category>

<category id="ssl">
<title>Apache SSL/TLS Encryption</title>
<page separate="yes" href="ssl/">Overview</page>
<page href="ssl/ssl_intro.html">SSL/TLS Encryption: An Introduction</page>
<page href="ssl/ssl_compat.html">SSL/TLS Encryption: Compatibility</page>
<page href="ssl/ssl_howto.html">SSL/TLS Encryption: How-To</page>
<page href="ssl/ssl_faq.html">SSL/TLS Encryption: FAQ</page>
</category>

<category id="howto">
<title>Guides, Tutorials, and HowTos</title>
<page separate="yes" href="howto/">Overview</page>
<page href="howto/auth.html">Authentication</page>
<page href="howto/cgi.html">Dynamic Content with CGI</page>
<page href="howto/ssi.html">Introduction to Server Side Includes</page>
<page href="howto/htaccess.html">.htaccess files</page>
<page href="howto/public_html.html">Per-user web directories</page>
<page href="misc/tutorials.html">Apache Tutorials</page>
</category>

<category id="platform">
<title>Platform-specific Notes</title>
<page separate="yes" href="platform/">Overview</page>
<page href="platform/windows.html">Using Apache with Microsoft
Windows</page>
<page href="platform/win_compiling.html">Compiling Apache for
Microsoft Windows</page>
<page href="platform/netware.html">Using Apache with Novell NetWare</page>
<page href="platform/perf-hp.html">Running a High-Performance Web
Server on HPUX</page>
<page href="platform/ebcdic.html">The Apache EBCDIC Port</page>
</category>

<category id="programs">
<title>Apache HTTP Server and Supporting Programs</title>
<page separate="yes" href="programs/">Overview</page>
<page href="programs/httpd.html">Manual Page: httpd</page>
<page href="programs/ab.html">Manual Page: ab</page>
<page href="programs/apachectl.html">Manual Page: apachectl</page>
<page href="programs/apxs.html">Manual Page: apxs</page>
<page href="programs/dbmmanage.html">Manual Page: dbmmanage</page>
<page href="programs/htdigest.html">Manual Page: htdigest</page>
<page href="programs/htpasswd.html">Manual Page: htpasswd</page>
<page href="programs/logresolve.html">Manual Page: logresolve</page>
<page href="programs/rotatelogs.html">Manual Page: rotatelogs</page>
<page href="programs/suexec.html">Manual Page: suexec</page>
<page href="programs/other.html">Other Programs</page>
</category>

<category id="misc">
<title>Apache Miscellaneous Documentation</title>
<page separate="yes" href="misc/">Overview</page>
<page href="misc/custom_errordocs.html">International Customized Server Error Messages</page>
<page href="misc/fin_wait_2.html">Connections in FIN_WAIT_2 and Apache</page>
<page href="misc/known_client_problems.html">Known Client Problems</page>
<page href="misc/descriptors.html">Descriptors and Apache</page>
<page href="cgi_path.html">PATH_INFO Changes in the CGI Environment</page>
</category>

<category id="modules">
<title>Apache modules</title>
<page href="mod/">Module index</page>
<page href="mod/directives.html">Directive index</page>
<page href="mod/quickreference.html">Directive Quick-Reference</page>
&allmodules;
</category>

<category id="developer">
<title>Developer Documentation</title>
<page separate="yes" href="developer/">Overview</page>
<page href="developer/API.html">Apache API notes</page>
<page href="developer/debugging.html">Debugging Memory Allocation in APR</page>
<page href="developer/documenting.html">Documenting Apache 2.0</page>
<page href="developer/hooks.html">Apache 2.0 Hook Functions</page>
<page href="developer/modules.html">Converting Modules from Apache 1.3 to Apache 2.0</page>
<page href="developer/request.html">Request Processing in Apache 2.0</page>
<page href="developer/filters.html">How Filters Work in Apache 2.0</page>
</category>

<category id="descriptive">
<title>Descriptive Information</title>
<page href="mod/module-dict.html">Definitions of terms used to describe Apache modules</page>
<page href="mod/directive-dict.html">Definitions of terms used to describe Apache directives</page>
<page href="glossary.html">Glossary</page>
<page>Sitemap (this document)</page>
</category>

</sitemap>
